//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTag
    {
        public long ContentID { get; set; }
        public string TagID { get; set; }
    }
}
